<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>#9.2 Exception Handling |  Multiple Catch blocks | Coder Coacher - Coaching Coders</title><meta content="#9.2 Exception Handling |  Multiple Catch blocks - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Telusko-Learnings/">Telusko Learnings</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>#9.2 Exception Handling |  Multiple Catch blocks</b></h2><h5 class="post__date">2018-03-16</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/X5urP793On8" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">you
so we have talked about try-catch and
finally right
what we'll do now is let's say in this
example I'm creating an a D so we say
int a addict we'll say Neil and the size
of this array is that says six so we
have an array of six elements here right
and if I try to access the fifth element
which is a or four into the fifth
element right and if I set the value
eight there's nothing wrong in that
so this is a normal statement and if you
on this code we got the output as 3 and
by but what if by mistake if I it's 6
I'm trying to access the last element
and the last element of the array as we
know should be 5 right because index
number starts with 0 it should be 5 but
mine is take out and writing 6 and if I
run this code you can see it is not
giving you proper answer it is giving
you an error it's because you are trying
to access the element which is not there
so you get a new error which is array
index out of bounds exception now this
is not the exception which you are
handling right even if you are using try
catch you are not specifying the
exception which it rose you're only
handling one exception so in order to
handle this one also what you can do is
you can write one more catch so we can
have multiple cats in our code so we can
say array index out of bounds exception
we can say e and we'll print the message
as error but I feel that doesn't look
good right because both this are
printing the same exception either error
I'm going to let's try to do that first
let's run this code it is working you're
getting the error but don't think we can
we have the same thing two times so when
you want to do same thing multiple times
what you can do is we can write multiple
catch odd we can write multiple
exception in one catch
something in this way I can just give a
pipe symbol there and we can do that so
we don't have tried multiple caches and
if you're on this code you can see we
got the same output now since both the
exceptions wanted to print same error
and it works in that way right and this
concept of having multiple exception in
one catch was introduced in one point
seven it was not there earlier if you're
using one point seven in your machine
this will work I mean one point seven on
later if you are using one point
six in your machine this will not work
okay so you can write you cannot write
multiple catch or multiple exception in
one catch if you are using one point six
and below let's go back to my earlier
way of writing which is having multiple
catch with multiple exception why I want
to go for multiple caches because I want
to play in different message I want to
play message here as cannot divide by
zero because that will make sense to the
user right instead of giving them either
which doesn't make any sense we should
be printing cannot divide by zero and
here we say stay in your limit it's
because you know we are we are going
beyond the array size right if I on this
code now it says stay in your limit okay
because it is executing the second catch
but you can if you if I change the value
of J to zero and if it on this phone you
are still getting only one exception not
the second one now why not the cannot
divide by zero except eyes because as
soon as you get exception here it will
die a jump to catch statement right so
this code will is not X getting executed
so that's the reason why it is spending
only one error but if I change this to
four and if I run this code it is it
will print the second error which is
cannot divide by zero so that's how you
can write multiple catch but just
imagine in this code if you have let's
say you happen to have one more
exception I don't know which exception
but let's say we have one more exception
here which is which even I don't know
what exception will be having or maybe
if I remove this thing if I try it if I
try to do this okay let's try so am i
signing a null value and I'm just trying
to face the value and you can see it is
giving you an exception which is null
point exception now this is one more
exception which we are not handling and
I can we can write one more catch block
which will handle null point exception
but after writing that let's say if I
have one more exception which I don't
know so in this scenario it is always
better to be on the safe side to use or
to use the last catch block as only the
exception block will print something
wrong because why exception is because
all the classes all the classes in
exception hierarchy are the subclasses
of exception right so it doesn't matter
which exception you have it will handle
everything
so if I'm this cold you can see we're
getting something wrong because it is
null point exception so what is
happening is as soon as you're getting
null point exception here it is first
checking with the first care first catch
it says okay I am NOT handling null
point exception even this cat says I am
not handling null point exception this
this catch says a height I'm not
handling null point exception but I can
do it because I'm exception I am the
anti Superman I can I can do everything
I can handle all the exceptions but what
will happen if you try to put this in
the front now this will give you an
accept this will give you an error
alright because let's say you are
getting on the point exception null
point exception is handled by this
exception if you are getting let's say
you are not getting the point exception
if I say new ain't and the size let's
say five so I will not have any
exception here right on this line but I
will be having exception on this line
which is a determining exception so if
you have an item the exception this cat
will handle that right because exception
can handle any exception doesn't matter
which exception you are talking about so
if this can do this except this catch
block and X can handle everything why do
we need this cache block right and
that's the - the issue it is it is
showing you why we need this catch block
that's the - the exception it is showing
you can see unreachable catch block for
a thematic which is already expanded by
catch block for exception so this catch
is handling everything and that's why
you have to make sure that the exception
cache block is at the end to make it run
smoothly so that's it we can have we can
write multiple cache block and you're
nuts it in the next video we'll talk
about checked exceptions</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>