<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>#9.5 Exception Handling | User Defined | Coder Coacher - Coaching Coders</title><meta content="#9.5 Exception Handling | User Defined - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/Telusko-Learnings/">Telusko Learnings</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>#9.5 Exception Handling | User Defined</b></h2><h5 class="post__date">2018-03-21</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/KFoN6hQ3yAs" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">so in this video we'll see how to create
our own exception
now just to demonstrate that let me
again take two variables which we are
doing from a long time and let us let me
assign the value of I as eight and J as
let's say zero and you know what I'm
going to do now is write I would say in
k equal to I divided by J we are doing
this for a long time now I will check if
let's say I'm dividing the number I'm
just printing the value of K as it is
now before printing the value we should
we should make sure that we are handling
the exception right so when your videos
try catch again since the same example
which we have done earlier so this is
what we have we have done earlier so we
are dividing number by number by J and
then of course it will give you an
exception so it will print the error
here but what I want to do now is if I
change the value to seven okay and or
maybe nine so it will give you the value
of value of K as zero right and we don't
want that so what we want is if there is
if my K value is zero it should it
should print error so we say if my K
value is equal equal to zero then throw
new exception and we have done that at
the other right we have done that so now
if I run this code you can see it is
calling adult so that means even if
there is no exception you can generate
or you can call the exception but it's I
don't want to call exception I want to
create my own exception here I will say
this is telesco exception now you can
see it is giving you an error we don't
have an exception name deceptive
exception if you don't have a class with
that is the exception let's create it
right so what we'll do is we'll click on
this you can see that once you go on the
error it will give you the option there
and let me use that let me click click
on create class that is co exception
with LeConte finish it will give you a
new class here and you can see if you
want to create an exception simply
extend it by exception and that's how
you create an exception here right and
now if i find on this code you can see
we got error so we are throwing our own
exception here in fact we can accept our
own exception we
can say telescope exceptionally when
that will work so we are throwing
today's for exception and we are
accepting the respects Epson here but
what if I want to send a message example
if I say error and if I want to print E
and if you're on this code you can see
it is throwing an exception which is
error count dot that is code or 10 is
for exception but what I want to pass a
message I will say e dot get message so
every error has a message in it example
when you say divide by 0 it says slash
by 0
that's the message and you can see we
are getting a message which is valid
that means this ethought message has
nothing because there is code doesn't
have any message now how do we send a
message it's very simple simply pass a
message here we'll say this is not
possible I mean the value you are trying
was not possible but it is not accepting
is because you are creating an object by
passing a string that means you read a
constructor which accepts a string so
let's create a constructor here we'll
say the risco exception which accepts a
string as and that's it I think it
should work now so we are passing a
message and we are saying get message
and if I run this code oh I'll get you
saying knowledge now why is the case I'm
passing the thing right but the problem
is we are just passing it where I mean
how do we inform this get message that
you have to fetch the message from s now
if you go to exception class you can see
an exception class we have you see that
we have a message we are calling a super
method we are calling a super that means
it will call the throwable constructor
and you can see we have a passage here
so from our class when you say string s
that message should should reach here
how that is reaching from exception in
exception we are pass we are getting the
message and we are passing that message
in the super and the super method which
is passing to the constructor of
variable from our class also we have to
call super bypassing s so this message
which is this is not possible goes into
s
now that message from s goes into
exception which is message and from that
message goes on to the variable detail
message
so that's how it is working and you feel
on this code now you can see because
either this is not possible so if you
want to create an exception is not that
difficult created class named a class
and extend with exception create a
constructor which which accept the
string and read a construct Paul the
superclass constructor by writing super
so that's it that's how you create
user-defined exception and that's how
you can use it</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>