<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>Java Tutorial For Beginners 36 - Catching and Handling Exceptions  in Java using Try Catch Blocks | Coder Coacher - Coaching Coders</title><meta content="Java Tutorial For Beginners 36 - Catching and Handling Exceptions  in Java using Try Catch Blocks - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/ProgrammingKnowledge/">ProgrammingKnowledge</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>Java Tutorial For Beginners 36 - Catching and Handling Exceptions  in Java using Try Catch Blocks</b></h2><h5 class="post__date">2015-06-10</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/YCalEDpu2oA" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">hello guys welcome to the next video on
Java programming tutorial for beginners
in this video we will see what is an
exception in Java and how we can handle
exceptions in Java using try catch block
so first of all what is an exception by
the official definition an exception is
an event which occurs during the
execution of the program which can
disrupt the normal flow of the program's
instruction ok so let me give you an
example for example I declare an integer
variable and I initialize it by some
value for example 100 okay and then I
divide it by 0 and we all know that
whenever some integer is divided by 0 it
gives us infinity and Java program is
not able to handle this situation
right so let's try to print something
for example this out and I'm going to
print this line after the Declaration of
this variable like this so when I run
the program if I see this that means
this declaration is valid for me right
because this initialization is
successful and I will be able to see
this line if I will not be able to see
this line that means the initialization
fails so I'm going to save this program
and I'm going to run my program and you
see in the console the exception in
thread mean occurs and Java gives us the
location of the exception or error and
this is at line 6 which is this one
right and which exception occurs here
are a thematic exception occurs so this
infinity is not handled by the Java okay
now in these situation where
our Java is not able to handle this
exceptional situation what we can do is
we can catch this exception by using a
try/catch block so normally how we can
write a try-catch block just write try
and then this curly braces and end the
curly brace and after that you need a
catch
so catch and in the brackets you give
the situation which you want to handle
and in here in the catch you can print
the situation or you can do whatever you
want to do after handling the
exceptional situation okay so now I'm
going to place my code inside this try
catch block okay and here is the
exception we want to handle so this code
is throwing this exception called
arithmetic exception okay
so we want to handle this here so just
write arithmetic exception and then give
the variable name okay and in here you
can even print this value of the
exception which is thrown which is this
exception exactly but let's run the
program and then see what happens so now
when I run the program I can see this
line printed that means the exception is
thrown but it's caught by this try catch
block and then we come to the next line
of code and we are able to print this
line now in order to handle the
situation after the exception so for
example we want to know which exception
is thrown by this try catch block inside
this we can handle this situation of
exception for example I want to print
this exceptional situation so this are a
thematic exception will handle this
infinity situation and we can print it
using this
II object of an automatic operation so
we to print this exception we can just
write system.out.print line and II okay
and let's save this program and run it
once again and now we can see this
exception is printed this is due to this
line okay and then our normal program
execution is happening which is printing
this line okay now in this try-catch
block you can add multiple catch block
so you can handle multiple you know
exceptional situations okay so for
example I can do something like this I'm
catching this exceptional automatic as
exception and I want to handle one more
exception which is the general kind of
exception I don't know what kind of
exception this is this so I will use
this general exception okay and then I'm
going to print this okay and now also
it's going to execute the same program
in the same way but in the case of
exception other than this exception
which is this one this code is going to
execute okay so now let's add some more
exceptional situation so for example I
will declare a variable which is an
array outside my try-catch block and
inside my try-catch block I want to
print the third element of the array we
know that the initialization of array is
with index two so third element is out
of scope of this array right so let's
print this and I'm going to declare it
as variable B because a is already here
okay and I'm going to print here the
value of B 3 so the value of B at index
3 okay
and I'm just going to write
and plus okay this I want to execute now
let's see what happens I'm going to save
this program and run this and it's going
to give me this automatic up or
exception once again due to this line so
let's let me comment this line for now
okay and let me save this once again and
run the program once again and now you
can see this exception different
exception is thrown and which is caught
by this bigger exception or the
exception which has a more priority for
example okay so this exception which is
array index out of bounds exception is
handled by this general exception here
which is this line okay so if you don't
believe me let's comment this code and
this code here okay so and let's run the
program once again and you see the same
exception so it is caught by this
exception okay you can even do just copy
this exceptional condition here and
paste it here okay and then it's going
to give the same result which is array
index out of bounds exception
okay so exception class is a general
class if you don't know which exception
is thrown by your code you can use this
exception otherwise if you know that
your code can you know throw arithmetic
exception or array index out of bounds
exception then you can you know handle
the specific exception and always
remember that you can add multiple catch
blocks with your try block okay so one
catch block to catch block you can even
handle three cache block and in this
situation for example I want to handle
this array index out of bound
and when you do something like this is
going to give you this error bubble here
and it says unreachable catch or let me
save the program and run it and let's
say what it says it's a unreachable
catch block why because this general
exception class has more priority than
this array index out of bounds exception
so this should come at the last okay so
when I do something like this I'm going
to cut this and I'm going to paste just
below this array out of bound exception
here then my error will be gone so
always remember this exception class
should go at the last okay and other
exception like arithmetic or index out
of bound will be above it because they
have the lesser priority okay and it's
this exception is more general exception
you want to handle okay so in this way
exception works in Java and you can
handle exceptions using try catch block
I hope you enjoyed this video please
rate comment subscribe and bye for now</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>