<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>Java Tutorial For Beginners 37 - Java Finally block (try-catch-finally Exception Handling in Java ) | Coder Coacher - Coaching Coders</title><meta content="Java Tutorial For Beginners 37 - Java Finally block (try-catch-finally Exception Handling in Java ) - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin, machine learning, AI, ML, tech talks, angular, javascript, js, typescript"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/ProgrammingKnowledge/">ProgrammingKnowledge</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>Java Tutorial For Beginners 37 - Java Finally block (try-catch-finally Exception Handling in Java )</b></h2><h5 class="post__date">2015-06-11</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/nuYdT5q3Gxc" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">hello guys welcome to the next video on
Java programming tutorial for beginners
in the last video we have seen how to
use try-catch block with our java code
in this video we will see what is
finally block in Java and how we can use
it with try-catch block in Java so first
of all what is a finally block the
finally block always executes when the
try block exists okay so generally you
use finally block when you want to add a
try-catch block with your code okay and
the property of finally block is it
always executes whether your exception
occurs or it doesn't occur it doesn't
matter what the code does it throws
exception or it doesn't throw exception
this finally block is always executed
so using this finally block you have
always the chance to release your
resources okay so let me give you an
example in the last video we have seen
that we can use a try-catch block
something like this and this is the code
which throws an exception because any
integer which is divided by 0 will give
an infinity and then Java will throw an
exception for that and which exception
is throws it throws arithmetic exception
right now to add a finally block to a
try-catch block what we can do is we can
just write finally and then in the curly
braces you can close it ok so this is
how you add finally block to your pry
cache block and the property of this is
it's always executed so for example I
can print something here for example
finally called ok
and let's add this print message here
and here we can say catch called okay
and let's save the program and run the
program and in here you see here it
gives you this finally called message
right and when I just scroll a little
bit above it prints catch that means
this code throws an exception and then
this line is printed and then it prints
the exception which is which have
occurred and then at the end when the
exception is thrown and caught by this
catch block at the end this finally will
execute okay
and this makes sure that you can release
all your resources or this can be used
to you know do the final work whatever
you want to do after the exception or
even if the exception doesn't happen
then also you can use finally in most of
the situations okay so it's a good
practice to use finally with your try
catch block okay and there is only one
situation where this finally block will
not be called and this situation is when
you call a system dot exit method inside
your try block so for example I do
something like this system dot exit with
some integer here for example 1 and I
will comment this code and when I run
the code then what happens see nothing
happens why because we have called
system dot exit and it exits from the
program and this is the only situation
where this finally will not be called in
any other situation if the exception is
thrown is if the exception is not thrown
finally will be called ok now to
understand this situation in a better
way let's create a method for example
public
attic void or let's return integer here
and let's say return int okay let's say
this method only returned integer okay
so and inside this I'm just going to
copy and cut this code which I have in
the main and paste it here okay and in
the last at the last what I want to do
is I want to return some integer so for
example I want to return the value of a
right so I want to declare this a
outside my try block okay and for
example we don't divide this hundred by
zero so it's valid situation and we want
to return a right so in here I want to
delete this and I will return a okay and
for example it throws an exception and
it goes here I want to return a here
also and in here also I want to return a
okay so in finally block I want to
return in this situation we will see
later but for now I want to do something
like this and in here I just want to
call my system out so this out and in
here I just want to call my return int
method okay inside this okay so let's
run the program and let's see what
happens so I'm running the program
and it returns 100 and 100 is printed
here and then finally block is called
after the try block returns so even if
your function returns this finally block
will be called okay so it doesn't matter
if you return from try block generally
you would think that you are returning
from here
then after return no code will be
executed but for finally it's an
exception finally will be executed even
if you are returning in the try block or
even in the catch block also so let's
divide it by 100 or divide this by 0 not
here but for example 2 it here a is
equal to 8 divided by 0 okay so it will
throw right so it will go here and then
exception code will be called and then
let's see what happens so save the
program and run the program and once
again we can see catch is called so it
throws an exception it goes here and it
first of all it calls this finally block
which prints this message finally called
and then only we will be able to see
this hundred which is returned by this
return so it doesn't matter if you
return from the try block or catch block
finally will be called in that situation
also now there is one more situation
which can occur for example I want to
return from the finally block also so
for example right now I have assigned a
is equal to hundred right and in the
finally block I can override my return
value for example I can do something
like this a is equal to thousand or five
thousand okay and then I can return a
now what will be returned from here will
it return 100 or will it return 5000
let's see what will happen so let me do
this after this here and what I'm going
to do here I will
this program and I'm going to run it and
you can see that finally overrides your
return value also okay so ideally it
should return 100 if you don't return
from finally right so I don't want to
return from finally I will save it and
it will return 100 like this okay but
when you return from finally and you
want to change the value which you want
to return in finally then finally will
override your earlier return value for
example five thousand so I will save
this and run this and it will return
five thousand okay so in this way you
can use finally with your try/catch
block and always remember it's a good
practice to use finally with your
try-catch block so always try to use it
whenever you use try-catch blocks so I
hope you have enjoyed this video please
rate comment and subscribe and bye</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>