<!DOCTYPE html><html lang="en"><head><script async src="https://www.googletagmanager.com/gtag/js?id=UA-114897551-4"></script><script>window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-114897551-4');
</script><script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5ac2443d1fff98001395ab6c&amp;product=sticky-share-buttons" async="async"></script><title>Error handling in JavaScript | Coder Coacher - Coaching Coders</title><meta content="Error handling in JavaScript - All technical stuff in one place" name="description"><meta name="keywords" content="education, coding, programming, technology, nodejs, mongodb, software, computer science, engineering, teaching, coaching, coder, learning, java, kotlin"><meta name="viewport" content="width=device-width, initial-scale=1.0"><link rel="stylesheet" href="/css/font.css"><link rel="stylesheet" href="/css/bootstrap.css"><link rel="stylesheet" href="/css/style.css"><link rel="stylesheet" href="/css/coder-coacher.css"></head><body><div class="container-fluid"><h1 class="site-title"><a href="/">Coder Coacher</a></h1><hr><h4 class="site-subtitle text-right">Coaching Coders</h4></div><div id="amzn-assoc-ad-99d6751e-2392-4004-ad16-73aa8385d9d0"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=99d6751e-2392-4004-ad16-73aa8385d9d0"></script><div class="post__breadcrumb"><div class="container"><ol class="breadcrumb"><li><a href="/">Coder Coacher</a></li><li><a href="/kudvenkat/">kudvenkat</a></li><li class="active">â¤µ</li></ol></div></div><h2 class="post__title"><b>Error handling in JavaScript</b></h2><h5 class="post__date">2015-01-04</h5><div class="container"><div class="video-responsive"><iframe width="560" height="315" src="https://www.youtube.com/embed/79RjHaAYT-4" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe></div><div class="post__text">this is part 31 of JavaScript tutorial
in this video we'll discuss error
handling in JavaScript use try catch
finally to handle runtime errors in
JavaScript these runtime errors are
called exceptions an exception can occur
for a variety of reasons for example
referencing a variable or a method that
is not defined can cause an exception
the JavaScript statements that can
possibly cause exceptions should be
wrapped inside a try block when a
specific line in the try block causes an
exception the control is immediately
transferred to the Associated catch
block skipping the rest of the lines in
the try block let's look at an example
any code that can possibly cause an
exception should be wrapped inside a try
block so here we are calling a function
that is not defined so this line can
cause an exception because we are
referencing a function that does not
exist when an exception occurs the
control is immediately transferred to
the catch block and the exception object
is passed to that catch block this
exception object has got different
properties like message description
stacktrace let's print what those
properties have got so first let's print
what's there in the message property and
to retrieve the message property use the
exception object and let's also plant an
HTML break
so description equals e dot description
and stacktrace is present in stack
property now we know that this line is
going to this line right here is going
to cause an exception when an exception
occurs the control is immediately
transferred to the Associated catch
block that means if we have a line here
this line will not be executed
right so this line will be skipped
execution the control will be
transferred to the cache block all these
lines within the cache block will be
executed and if we have any line present
after the catch block that line will be
executed so let's look at this in action
let's run this notice that we have the
three properties of the exception object
printed there and then notice what we
have we have this message this line will
be executed that means this line is
executed but this line is skipped
execution try block should be followed
by a catch block or finally block or
even both finally block is guaranteed to
execute irrespective of whether there is
an exception or not finally block is
generally used to clean and free
resources that the script was holding on
to during the program execution for
example let's say your script in the try
block has opened a file for processing
and then if there is an exception after
the file has been opened then the
finally block can be used to close that
file let's look at an example so at the
moment we have here try and catch let's
include finally block as well and within
finally block let's include this line
this line is guaranteed to execute
now at the moment the code right here is
going to cause an exception so when an
exception occurs now the control will be
immediately transferred to the
Associated catch block so these lines
will be executed and then you know after
it finishes executing the code in the
cache block the code in the finally
block is guaranteed to execute so let's
see that so notice that we have the
exception properties printed and then
this line is guaranteed to execute so
the code within the finally block is
executed now in this example this line
is throwing an exception now let's say
you know we just want to print this
furred hello let's also print HTML break
so now when we run this code we will not
have an exception so when there is an
except when when an exception is not
there will the finally block be executed
yes let's prove that
notice that the message hello is printed
again the code within finally block is
also executed so irrespective of whether
there is an exception or not the finally
block is guaranteed to execute that's
why this is the right place to include
any code that you want to perform
cleanup syntax errors and exceptions in
JavaScript try catch finally block and
catch exceptions but not syntax errors
so if you look at the example right here
we've got a syntax error notice that
here we are missing the closing
parenthesis for the alert function so
when we run this program we will have a
syntax error but this syntax error is
not going to cause the control to be
transferred to the associated catch
block because we cannot use try catch
finally to catch syntax errors throwing
exceptions we use through statement in
JavaScript to raise a customized
exception let's look at an example let's
say we want to write a function to
divide two numbers so let's call the
function divided and we want to prompt
the user to enter numerator and
denominator so let's use the prompt
function for that
please enter numerator and when the end
user enters in number we want to convert
that to a number using the number
function and then store it in a variable
called numerator similarly we want to
prom the end user to enter denominator
and then store that in this variable
denominator so any code that we are
going to have now let's wrap that inside
this try block so if denominator is 0
now that's illegal in a division
denominator cannot be zero so if
denominator is zero then I'm going to
throw a customized exception using the
throw keyword and the object that I'm
going to throw is going to have these
two properties error and let's say the
error is divided by zero error and it is
also going to have message property and
the message property is going to say
denominator cannot be zero so we we are
throwing this customized exception if
the denominator is zero
if the denominator is not zero then we
want to perform the division and then
print the result
so let's use document.write and then
let's say result equals numerator by
denominator so if any code here is going
to cause an exception the control will
be immediately transferred to the catch
block and the exception object will be
passed to the catch block and what we
want to do is retrieve these two
properties that is error and message and
display them on the page so document dot
write error equals e dot error and let's
also include HTML break
and message equals e dot message right
so we have a very simple divide function
so let's go ahead and call the divide
function all right let's run this now so
it's prompting us to enter numerator
let's pass 10 as the numerator it's
asking us to enter denominator
let's pass 2 as the denominator so when
we click OK it should print result is 5
let's reload this page enter 10s
numerator and 0's denominator so when
denominator is 0 it's going to throw
this customized exception and when an
exception is thrown you know that
exception will be passed to the
Associated catch block and within the
catch block here we are catching that
exception and then printing whatever we
have caught in error
and message properties so that means we
should have I mean we should get these
two messages printed on the page so
let's click OK notice that we get error
and message thank you for listening and
have a great day</div></div><div class="container-fluid bottom-ad"><div id="amzn-assoc-ad-6a809dda-347a-4187-8a86-91faf94575da"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&amp;adInstanceId=6a809dda-347a-4187-8a86-91faf94575da"></script></div><div class="text-center">We are a participant in the Amazon Services LLC Associates Program, an affiliate advertising program designed to provide a means for us to earn fees by linking to Amazon.com and affiliated sites.</div><script>(function(w, d){
    var b = d.getElementsByTagName('body')[0];
    var s = d.createElement("script"); s.async = true;
    var v = !("IntersectionObserver" in w) ? "8.6.0" : "10.4.2";
    s.src = "https://cdnjs.cloudflare.com/ajax/libs/vanilla-lazyload/" + v + "/lazyload.min.js";
    w.lazyLoadOptions = {};
    b.appendChild(s);
}(window, document));</script></body></html>